import { enableGADebug } from '@lcrespilho/playwright-utils'
import { test, expect } from '@lcrespilho/playwright-fixtures'

declare global {
  interface Element {
    content: any
  }
  interface HTMLCollection {
    providerID: Element
  }
}

test.setTimeout(120000)
test.use({ ga4HitRegex: /google.*collect\?v=2.*G-LRELP0EZ4X.*en=page_view/ })

const sites = [
  'https://www.greenwayhyundaishoals.com,231,DealerOn', // net::ERR_CERT_COMMON_NAME_INVALID
  'https://www.hornehyundai.com,Dealer eProcess,Dealer eProcess', // VPN
  'https://www.fontanahyundai.com,Dealer eProcess,Dealer eProcess', // VPN
  'https://www.harbor-hyundai.com,Dealer eProcess,Dealer eProcess', // VPN
  'https://www.hyundaicarson.com,Dealer eProcess,Dealer eProcess', // VPN
  'https://www.downeyhyundai.com,Dealer eProcess,Dealer eProcess', // VPN
  'https://www.tustinhyundai.com,Dealer eProcess,Dealer eProcess', // VPN
  'https://www.platinumhyundaioftracy.com,Dealer eProcess,Dealer eProcess', // VPN
  'https://www.lithiahyundaianchorage.com,DDC,DDC',
  'https://www.hyundaiofdothan.com,DDC,DDC',
  'https://www.tuscaloosahyundai.com,251144,Dealer Inspire',
  'https://www.jimburkebirminghamhyundai.com,251144,Dealer Inspire',
  'https://www.bentleyhyundai.com,251144,Dealer Inspire',
  'https://www.superiorhyundaial.com,sincro,sincro',
  'https://www.hyundaiofgadsden.com,251144,Dealer Inspire',
  'https://www.mitchellhyundai.com,DDC,DDC',
  'https://www.easternshorehyundai.com,251144,Dealer Inspire',
  'https://www.palmershyundai.com,sincro,sincro',
  'https://www.tameronhyundai.com,251144,Dealer Inspire',
  'https://www.greenwayhyundaiofdecatur.com,251144,Dealer Inspire',
  'https://www.hyundaiofjasper.com,sincro,sincro',
  'https://www.serrahyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofauburn.com,251144,Dealer Inspire',
  'https://www.HyundaiMontgomery.com,251144,Dealer Inspire',
  'https://www.cavenaughhyundai.com,231,DealerOn',
  'https://www.cavenaughhyundaihotsprings.com,231,DealerOn',
  'https://www.crainhyundailittlerock.com,231,DealerOn',
  'https://www.crainhyundainorth.com,231,DealerOn',
  'https://www.smartdrivehyundai.com,sincro,sincro',
  'https://www.crainhyundaioffayetteville.com,231,DealerOn',
  'https://www.crainhyundaibentonville.com,231,DealerOn',
  'https://www.crainhyundaiftsmith.com,231,DealerOn',
  'https://www.orrhyundai.net,DDC,DDC',
  'https://www.chriscrainhyundai.com/,231,DealerOn',
  'https://www.jimclickhyundaiautomall.com,231,DealerOn',
  'https://www.jimclickhyundaieast.com,231,DealerOn',
  'https://www.hdhyundai.com,DDC,DDC',
  'https://www.lawleyhyundai.com,sincro,sincro',
  'https://www.hyundaigreenvalley.com,231,DealerOn',
  'https://www.hyundaiofphoenixaz.com,DDC,DDC',
  'https://www.hyundaiofcottonwood.com,DDC,DDC',
  'https://www.santanhyundai.com,231,DealerOn',
  'https://www.hyundaiofscottsdale.com,DDC,DDC',
  'https://www.earnhardthyundai.com,231,DealerOn',
  'https://www.northscottsdalehyundai.com,231,DealerOn',
  'https://www.oxendalehyundai.com,231,DealerOn',
  'https://www.autonationhyundaitempe.com,DDC,DDC',
  'https://www.camelbackhyundai.com,DDC,DDC',
  'https://www.Hyundaiofyuma.com,DDC,DDC',
  'https://www.kengarffhyundaisurprise.com,251144,Dealer Inspire',
  'https://www.larrymillerhyundai.com,DDC,DDC',
  'https://www.findlayhyundaiprescott.com,231,DealerOn',
  'https://www.lagunaniguelhyundai.com,251144,Dealer Inspire',
  'https://www.cardinalewayhyundaiglendora.com,dealeron,DealerOn',
  'https://www.powayhyundai.com,DDC,DDC',
  'https://www.fremonthyundai.com,251144,Dealer Inspire',
  'https://www.stevenscreekhyundai.com,251144,Dealer Inspire',
  'https://www.diamondhyundaipalmdale.com,sincro,sincro',
  'https://www.vallejohyundai.com,251144,Dealer Inspire',
  'https://www.visaliahyundai.com,DDC,DDC',
  'https://www.glendalehyundai.com,DDC,DDC',
  'https://www.cardinalewayhyundaiofelmonte.com,231,DealerOn',
  'https://www.hyundaiofsanbruno.com,231,DealerOn',
  'https://www.hyundaioflosangeles.com,231,DealerOn',
  'https://www.hanfordhyundai.com,DDC,DDC',
  'https://www.autonationhyundaivalencia.com,DDC,DDC',
  'https://www.hyundaisantamonica.com,DDC,DDC',
  'https://www.autonationhyundaicarlsbad.com,DDC,DDC',
  'https://www.hyundaiofmorenovalley.com,251144,Dealer Inspire',
  'https://www.hyundaidalton.com/,231,DealerOn',
  'https://www.manlyhyundai.com,251144,Dealer Inspire',
  'https://www.northwoodhyundai.com,sincro,sincro',
  'https://www.ontariohyundai.com,251144,Dealer Inspire',
  'https://www.chicohyundai.com,251144,Dealer Inspire',
  'https://www.goschhyundai.com,251144,Dealer Inspire',
  'https://www.lithiahyundaioffresno.com,DDC,DDC',
  'https://www.selmahyundai.com,DDC,DDC',
  'https://www.riversidehyundai.net,DDC,DDC',
  'https://www.rosevillehyundai.com,251144,Dealer Inspire',
  'https://www.victorvillehyundai.com,DDC,DDC',
  'https://www.kearnymesahyundai.com,251144,Dealer Inspire',
  'https://www.cardinalewayhyundai.com,dealeron,DealerOn',
  'https://www.capitolhyundaisj.com,251144,Dealer Inspire',
  'https://www.centralvalleyhyundai.com,251144,Dealer Inspire',
  'https://www.futurehyundaiofconcord.com,DDC,DDC',
  'https://www.hyundaioflaquinta.com,sincro,sincro',
  'https://www.elkgrovehyundai.com,251144,Dealer Inspire',
  'https://www.tuttleclickhyundai.com,DDC,DDC',
  'https://www.dublinhyundai.com,231,DealerOn',
  'https://www.phhyundai.com,251144,Dealer Inspire',
  'https://www.normreeveshyundai.com,251144,Dealer Inspire',
  'https://www.allstarhyundai.net,251144,Dealer Inspire',
  'https://www.mercedhyundai.com,sincro,sincro',
  'https://www.sbhyundai.com,DDC,DDC',
  'https://www.folsomlakehyundai.com,251144,Dealer Inspire',
  'https://www.palmspringshyundai.com,DDC,DDC',
  'https://www.hanleeshilltophyundai.com,251144,Dealer Inspire',
  'https://www.stocktonhyundai.com,251144,Dealer Inspire',
  'https://www.hyundaivacaville.com,251144,Dealer Inspire',
  'https://www.temeculahyundai.com,DDC,DDC',
  'https://www.ivhyundai.com,sincro,sincro',
  'https://www.gardengrovehyundai.com,DDC,DDC',
  'https://www.huntingtonbeachhyundai.com,DDC,DDC',
  'https://www.hyundaiofanaheim.com,DDC,DDC',
  'https://www.hyundaiescondido.com,DDC,DDC',
  'https://www.sanleandrohyundai.com,231,DealerOn',
  'https://www.westlakehyundai.com,DDC,DDC',
  'https://www.premierhyundaiofseaside.com,251144,Dealer Inspire',
  'https://www.hyundaislo.com,DDC,DDC',
  'https://www.hyundaiofelcajon.com,DDC,DDC',
  'https://www.bakersfieldhyundai.com,DDC,DDC',
  'https://www.hyundaiofgilroy.com,sincro,sincro',
  'https://www.keyeshyundai.com,DDC,DDC',
  'https://www.mhhyundai.com,DDC,DDC',
  'https://www.hyundaispradley.com,DDC,DDC',
  'https://www.coloradospringshyundai.com,DDC,DDC',
  'https://www.mcdonaldhyundai.com,251144,Dealer Inspire',
  'https://www.planethyundai.com,251144,Dealer Inspire',
  'https://www.hyundaicoloradosprings.com,DDC,DDC',
  'https://www.hyundaiofgreeley.com,sincro,sincro',
  'https://www.mycrossroadshyundai.com,251144,Dealer Inspire',
  'https://www.redrockhyundai.com,251144,Dealer Inspire',
  'https://www.schomphyundai.com,251144,Dealer Inspire',
  'https://www.foundationhyundai.com,DDC,DDC',
  'https://www.hyundaiofboulder.com,DDC,DDC',
  'https://www.arapahoehyundai.com,DDC,DDC',
  'https://www.stevinsonhyundai.com,DDC,DDC',
  'https://www.mjsullivanhyundai.com,sincro,sincro',
  'https://www.torringtonhyundai.com,DDC,DDC',
  'https://www.meridenhyundai.com,251144,Dealer Inspire',
  'https://www.liahyundaiofhartford.com,231,DealerOn',
  'https://www.danburyhyundai.com,DDC,DDC',
  'https://www.liahyundaiofenfield.com,231,DealerOn',
  'https://www.keyhyundaimanchesterct.com,DDC,DDC',
  'https://www.keyhyundaimilfordct.com,DDC,DDC',
  'https://www.stamfordhyundai.com,DDC,DDC',
  'https://www.balisehyundaifairfield.com,251144,Dealer Inspire',
  'https://www.brandfonhyundai.com,DDC,DDC',
  'https://www.shakersfamilyhyundai.com,DDC,DDC',
  'https://www.wilehyundai.com,DDC,DDC',
  'https://www.shorelinehyundai.com,DDC,DDC',
  'https://www.centralhyundaict.com,DDC,DDC',
  'https://www.porterhyundai.com,DDC,DDC',
  'https://www.hertrichhyundaiofnewcastle.com,DDC,DDC',
  'https://www.winnerhyundai.com,DDC,DDC',
  'https://www.ftlauderdalehyundai.com,DDC,DDC',
  'https://www.potamkinhyundai.com,251144,Dealer Inspire',
  'https://www.coastalhyundai.com,sincro,sincro',
  'https://www.kinghyundai.com,251144,Dealer Inspire',
  'https://www.fitzclearwaterhyundai.com,DDC,DDC',
  'https://www.lakelandhyundai.com,231,DealerOn',
  'https://www.crownhyundai.com,DDC,DDC',
  'https://www.allenturnerhyundai.com/,251144,Dealer Inspire',
  'https://www.tampahyundai.com,DDC,DDC',
  'https://www.jenkinshyundaiofocala.com,DDC,DDC',
  'https://www.gettelhyundaiofsarasota.com,251144,Dealer Inspire',
  'https://www.cocoahyundai.com,sincro,sincro',
  'https://www.route60hyundai.com,231,DealerOn',
  'https://www.universal-hyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofgainesville.com,sincro,sincro',
  'https://www.wallacehyundaiofstuart.com,231,DealerOn',
  'https://www.rickcasehyundaidavie.com,DDC,DDC',
  'https://www.hyundaioforangepark.com,251144,Dealer Inspire',
  'https://www.jenkinshyundaiofleesburg.com,DDC,DDC',
  'https://www.wpbhyundai.com,DDC,DDC',
  'https://www.coconutcreekhyundai.com,DDC,DDC',
  'https://www.northpalmhyundai.com,DDC,DDC',
  'https://www.greenwayhyundaiorlando.com,251144,Dealer Inspire',
  'https://www.hollerhyundai.com,231,DealerOn',
  'https://www.redhoagland.com,sincro,sincro',
  'https://www.hyundaiofstaugustine.com,251144,Dealer Inspire',
  'https://www.wernerhyundai.com,251144,Dealer Inspire',
  'https://www.tamiamihyundai.com,251144,Dealer Inspire',
  'https://www.Bramanmiamihyundai.com,DDC,DDC',
  'https://www.westsidehyundai.com,251144,Dealer Inspire',
  'https://www.gettelhyundaioflakewood.com,251144,Dealer Inspire',
  'https://www.headquarterhyundai.com,251144,Dealer Inspire',
  'https://www.coggindelandhyundai.com,DDC,DDC',
  'https://www.gettelhyundaiofcharlottecounty.com,251144,Dealer Inspire',
  'https://www.keyhyundai.com,DDC,DDC',
  'https://www.hyundaicfl.com,251144,Dealer Inspire',
  'https://www.brandonhyundai.com,251144,Dealer Inspire',
  'https://www.jenkinshyundaiofjacksonville.com,DDC,DDC',
  'https://www.hyundaiofvenice.com,231,DealerOn',
  'https://www.HyundaiOfFortMyers.com,251144,Dealer Inspire',
  'https://www.hyundaiofnewportrichey.com,Dealer eProcess,Dealer eProcess',
  'https://www.hyundaiofwesleychapel.com,Dealer eProcess,Dealer eProcess',
  'https://www.panamacityhyundai.com,DDC,DDC',
  'https://www.delrayhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.wallacehyundaioffortpierce.com,231,DealerOn',
  'https://www.doralhyundai.com,251144,Dealer Inspire',
  'https://www.lehmanhyundai.com,251144,Dealer Inspire',
  'https://www.kendallhyundai.com,251144,Dealer Inspire',
  'https://www.rickcasehyundaiatlanta.com,DDC,DDC',
  'https://www.VoylesHyundai.com,251144,Dealer Inspire',
  'https://www.southtowneatlanta.com,DDC,DDC',
  'https://www.taylorhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.fivestarhyundaiofmacon.com,251144,Dealer Inspire',
  'https://www.southtownehyundai.com,DDC,DDC',
  'https://www.jimellishyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofkennesaw.com,231,DealerOn',
  'https://www.rickcasehyundairoswell.com,DDC,DDC',
  'https://www.warnerrobinshyundai.net,251144,Dealer Inspire',
  'https://www.terryreidhyundai.com,251144,Dealer Inspire',
  'https://www.autonationhyundaimallofgeorgia.com,DDC,DDC',
  'https://www.langdalehyundai.com,DDC,DDC',
  'https://www.volumehyundai.com,251144,Dealer Inspire',
  'https://www.nalleyhyundai.com,DDC,DDC',
  'https://autonationhyundaicolumbus.com,DDC,DDC',
  'https://www.jenkinshyundaioflithiasprings.com,DDC,DDC',
  'https://www.fivestarhyundaialbany.com,251144,Dealer Inspire',
  'https://www.mvhyundai.com,231,DealerOn',
  'https://www.hyundaibrunswick.com,231,DealerOn',
  'https://www.potamkinatlanta.com,251144,Dealer Inspire',
  'https://www.hyundaiofcumming.com,231,DealerOn',
  'https://www.shottenkirkhyundai.com,251144,Dealer Inspire',
  'https://www.autonationhyundaisavannah.com,DDC,DDC',
  'https://www.shottenkirkhyundairome.com,251144,Dealer Inspire',
  'https://www.mcdonoughhyundai.com,231,DealerOn',
  'https://www.Hyundaiofathens.com,231,DealerOn',
  'https://www.gainesvillehyundai.com,231,DealerOn',
  'https://www.kuhiohyundai.com,sincro,sincro',
  'https://www.tonyhyundai.com,231,DealerOn',
  'https://www.bigislandhyundai.com,251144,Dealer Inspire',
  'https://www.jimfalkhyundaiofmaui.com,DDC,DDC',
  'https://www.windwardhyundai.com,DDC,DDC',
  'https://www.jerryvhonoluluhyundai.com,DDC,DDC',
  'https://www.edwardshyundai.com,251144,Dealer Inspire',
  'https://www.candshyundai.com,DDC,DDC',
  'https://www.Smarthyundaidavenport.com,251144,Dealer Inspire',
  'https://www.iowacityhyundai.com,DDC,DDC',
  'https://www.stewhansenhyundai.com,251144,Dealer Inspire',
  'https://www.mcgrathhyundaiofdubuque.com,DDC,DDC',
  'https://www.mcgrathhyundaicr.com,DDC,DDC',
  'https://www.verneidehyundaisiouxcity.com,251144,Dealer Inspire',
  'https://www.broncomotorshyundai.com,DDC,DDC',
  'https://www.robgreenhyundai.com,DDC,DDC',
  'https://www.woodysmithhyundai.com,DDC,DDC',
  'https://www.broncomotorshyundaiwest.com,DDC,DDC',
  'https://www.gotomidwayhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.stoneshyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.napletonhyundaiglenview.com,Dealer eProcess,Dealer eProcess',
  'https://www.auffenberghyundai.com,sincro,sincro',
  'https://www.greenhyundai.com,DDC,DDC',
  'https://www.marionhyundai.com,DDC,DDC',
  'https://www.mikemillerhyundai.com,sincro,sincro',
  'https://www.kcsummershyundai.com,sincro,sincro',
  'https://www.gregoryhyundai.com,sincro,sincro',
  'https://www.bobbradyhyundai.com,251144,Dealer Inspire',
  'https://www.gurneehyundai.com,DDC,DDC',
  'https://www.darcyhyundai.com,DDC,DDC',
  'https://www.schimmerhyundai.com,DDC,DDC',
  'https://www.hyundaionperryville.com,Dealer eProcess,Dealer eProcess',
  'https://www.familyhyundai.com,251144,Dealer Inspire',
  'https://www.ettlesonhyundai.com,DDC,DDC',
  'https://www.elginhyundai.com,DDC,DDC',
  'https://www.patrickhyundai.com,251144,Dealer Inspire',
  'https://www.napletonriveroakshyundai.com,DDC,DDC',
  'https://www.worldhyundaimatteson.com,251144,Dealer Inspire',
  'https://www.mcgrathhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.wilkinshyundai.com,DDC,DDC',
  'https://www.geraldhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.myhappyhyundai.com,251144,Dealer Inspire',
  'https://www.napletonsvalleyhyundai.com,DDC,DDC',
  'https://www.greenfamilyhyundai.com,251144,Dealer Inspire',
  'https://www.autonationhyundaiohare.com,DDC,DDC',
  'https://www.rosenhyundai.com,DDC,DDC',
  'https://www.napletonshyundaiofurbana.com,DDC,DDC',
  'https://www.obrienteamhyundai.com,251144,Dealer Inspire',
  'https://www.phillipshyundai.com,DDC,DDC',
  'https://www.quincyhyundai.com,DDC,DDC',
  'https://www.hyundaioflincolnwood.com,251144,Dealer Inspire',
  'https://www.hyundaipalatine.com,251144,Dealer Inspire',
  'https://www.libertyvillehyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofsycamore.com,DDC,DDC',
  'https://www.napletondowntownhyundai.com,DDC,DDC',
  'https://www.castlehyundaidownersgrove.com,Dealer eProcess,Dealer eProcess',
  'https://www.rohrmanhyundai.com,DDC,DDC',
  'https://www.glenbrookhyundai.com,DDC,DDC',
  'https://www.indyhyundai.com,DDC,DDC',
  'https://www.gurleyleephyundai.com,251144,Dealer Inspire',
  'https://www.rayskillmansouthsidehyundai.com,251144,Dealer Inspire',
  'https://www.rayskillmanhyundaiwest.com,251144,Dealer Inspire',
  'https://www.webbhyundai.com,sincro,sincro',
  'https://www.dorsetthyundai.com,251144,Dealer Inspire',
  'https://www.andymohrhyundai.com,231,DealerOn',
  'https://www.hyundaimerrillville.com,sincro,sincro',
  'https://www.rayskillmanavon.com,251144,Dealer Inspire',
  'https://www.hyundaiofcarmel.com,DDC,DDC',
  'https://www.bachmanhyundai.com,251144,Dealer Inspire',
  'https://www.greghublerhyundai.com,251144,Dealer Inspire',
  'https://www.michigancityhyundai.com,DDC,DDC',
  'https://www.hyundaiofcolumbus.com,DDC,DDC',
  'https://www.hyundaiofnoblesville.com,DDC,DDC',
  'https://www.goshenhyundai.com,DDC,DDC',
  'https://www.hyundaiofevansville.com,DDC,DDC',
  'https://www.hatchetthyundaieast.com,sincro,sincro',
  'https://www.hyundaioftopeka.com,251144,Dealer Inspire',
  'https://www.mccarthyolathehyundai.com,sincro,sincro',
  'https://www.hyundaioflawrence.com,251144,Dealer Inspire',
  'https://www.hatchetthyundaiwest.com,sincro,sincro',
  'https://www.reedhyundaikc.com,251144,Dealer Inspire',
  'https://www.maxhyundaimanhattan.com,DDC,DDC',
  'https://www.hyundaidodgecity.com,251144,Dealer Inspire',
  'https://www.swopehyundai.com,251144,Dealer Inspire',
  'https://www.JimJohnsonHyundai.com,DDC,DDC',
  'https://www.thehyundaistore.net,DDC,DDC',
  'https://www.kerryhyundai.com,DDC,DDC',
  'https://www.gateshyundai.com,231,DealerOn',
  'https://www.oxmoorhyundai.com,251144,Dealer Inspire',
  'https://www.linwoodhyundai.com,DDC,DDC',
  'https://www.donmoorehyundai.com,231,DealerOn',
  'https://www.hyundaioflouisville.com,251144,Dealer Inspire',
  'https://www.timshorthyundai.com,DDC,DDC',
  'https://www.donfranklinlexingtonhyundai.com,DDC,DDC',
  'https://www.croninhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.donfranklinsomersethyundai.com,DDC,DDC',
  'https://www.navarrehyundai.com,DDC,DDC',
  'https://www.northparkhyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofbatonrouge-la.com,231,DealerOn',
  'https://www.gregleblanchyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.billhoodhyundai.com,sincro,sincro',
  'https://www.ralphsellershyundai.com,DDC,DDC',
  'https://www.sterlinghyundai.net,DDC,DDC',
  'https://www.hyundaiofmetairie.com,DDC,DDC',
  'https://www.interstatehyundai.com,DDC,DDC',
  'https://www.raybrandthyundai.com,251144,Dealer Inspire',
  'https://www.gileshyundai.com,DDC,DDC',
  'https://www.herbchambershyundaiofauburn.com,DDC,DDC',
  'https://www.mirakhyundai.com,DDC,DDC',
  'https://www.hyundaiofseekonk.com,DDC,DDC',
  'https://www.haddadhyundai.com,DDC,DDC',
  'https://www.garyromehyundai.com,DDC,DDC',
  'https://www.pridehyundai.com,251144,Dealer Inspire',
  'https://www.empirehyundai.com,DDC,DDC',
  'https://www.route44hyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.balisehyundaispringfield.com,251144,Dealer Inspire',
  'https://www.FIRSTHYUNDAI.COM,DDC,DDC',
  'https://www.countryhyundai.com,251144,Dealer Inspire',
  'https://www.balisehyundaiofcapecod.com,251144,Dealer Inspire',
  'https://www.mcgovernhyundai.com,DDC,DDC',
  'https://www.bochhyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofplymouth.com,DDC,DDC',
  'https://www.mcgovernhyundairt2.com,DDC,DDC',
  'https://www.quirkhyundai.com,251144,Dealer Inspire',
  'https://www.mcgovernhyundairt93.com,DDC,DDC',
  'https://www.metrowesthyundai.com,231,DealerOn',
  'https://www.mcgovernhyundaiofmilford.com,DDC,DDC',
  'https://www.pohankahyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.thompsonhyundai.com,DDC,DDC',
  'https://www.masseyauto.com,DDC,DDC',
  'https://www.idealhyundai.com,231,DealerOn',
  'https://www.gaithersburghyundai.com,DDC,DDC',
  'https://www.belairhyundai.com,DDC,DDC',
  'https://www.bobbellhyundai.com,251144,Dealer Inspire',
  'https://www.pohankahyundaimd.com,Dealer eProcess,Dealer eProcess',
  'https://www.lenstolerhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.antwerpencatonsvillehyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.teamhyundaimd.com,DDC,DDC',
  'https://www.antwerpenhyundaiclarksville.com,Dealer eProcess,Dealer eProcess',
  'https://www.fitzwayhyundai.com,DDC,DDC',
  'https://www.prestonhyundaiusa.com,231,DealerOn',
  'https://www.thomascumberlandhyundai.com,DDC,DDC',
  'https://www.ourismanhyundai.com,DDC,DDC',
  'https://www.annapolishyundai.com,DDC,DDC',
  'https://www.sheehyhyundaiwaldorf.com,Dealer eProcess,Dealer eProcess',
  'https://www.heritagehyundaibaltimore.com,DDC,DDC',
  'https://www.hyundaicarsofbowie.com,DDC,DDC',
  'https://www.collegeparkhyundai.com,251144,Dealer Inspire',
  'https://www.quirkhyundaiofbangor.com,251144,Dealer Inspire',
  'https://www.rowehyundaiauburn.com,DDC,DDC',
  'https://www.rowehyundai.com,DDC,DDC',
  'https://www.billdodgehyundai.com,sincro,sincro',
  'https://www.darlingshyundai.com,DDC,DDC',
  'https://www.glassmanhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.maplehillhyundai.com,DDC,DDC',
  'https://www.detroithyundai.com,251144,Dealer Inspire',
  'https://www.foxhyundai.com,DDC,DDC',
  'https://www.garberhyundai.com,251144,Dealer Inspire',
  'https://www.billmarshhyundai.com,DDC,DDC',
  'https://www.RandyWiseHyundai.com,231,DealerOn',
  'https://www.ferneliushyundai.com,DDC,DDC',
  'https://www.feldmanhyundai.com,231,DealerOn',
  'https://www.bettenbakerhyundai.com,251144,Dealer Inspire',
  'https://www.elderhyundai.com,DDC,DDC',
  'https://www.signaturehyundai.com,DDC,DDC',
  'https://www.foxannarborhyundai.com,DDC,DDC',
  'https://www.lansinghyundai.com,DDC,DDC',
  'https://www.suburbanhyundai.com,DDC,DDC',
  'https://www.lafontainehyundailivonia.com,251144,Dealer Inspire',
  'https://www.zeiglerhyundaiofholland.com,DDC,DDC',
  'https://www.kolarhyundai.com,231,DealerOn',
  'https://www.burnsvillehyundai.com,251144,Dealer Inspire',
  'https://www.buerklehyundai.com,DDC,DDC',
  'https://www.walserhyundai.com,251144,Dealer Inspire',
  'https://www.bloomingtonhyundai.com,251144,Dealer Inspire',
  'https://www.dondelingerhyundai.com,DDC,DDC',
  'https://www.Morries394Hyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofmankato.com,251144,Dealer Inspire',
  'https://www.invergrovehyundai.com,DDC,DDC',
  'https://www.stcloudhyundai.com,DDC,DDC',
  'https://www.walserhyundaicoonrapids.com,251144,Dealer Inspire',
  'https://www.rochesterhappyhyundai.com/,251144,Dealer Inspire',
  'https://www.northtownehyundai.com,DDC,DDC',
  'https://www.deanteamhyundai.com,DDC,DDC',
  'https://www.stcharleshyundai.com,DDC,DDC',
  'https://www.mccarthyhyundai.com,sincro,sincro',
  'https://www.suntruphyundaisouth.com,251144,Dealer Inspire',
  'https://www.fletcherhyundai.com,DDC,DDC',
  'https://www.reliablehyundai.com,DDC,DDC',
  'https://www.auffenbergcapehyundai.com,DDC,DDC',
  'https://www.joemachenshyundai.com,sincro,sincro',
  'https://www.napletonhyundai.com,DDC,DDC',
  'https://www.reedhyundai.com,251144,Dealer Inspire',
  'https://www.clementhyundai.com,DDC,DDC',
  'https://www.hyundaiofjeffersoncity.com,DDC,DDC',
  'https://www.mackgrubbshyundai.com,sincro,sincro',
  'https://www.jasonpilgerhyundai.com,DDC,DDC',
  'https://www.pridehyundaiinc.com,DDC,DDC',
  'https://www.homerskeltonhyundai.com,DDC,DDC',
  'https://www.bchyundaioftupelo.com,DDC,DDC',
  'https://www.MattBowersHyundai.com,DDC,DDC',
  'https://www.hallmarkhyundaiflowood.com,DDC,DDC',
  'https://www.hallmarkhyundainorth.com,DDC,DDC',
  'https://Www.hyundaiofmeridian.com,251144,Dealer Inspire',
  'https://www.underrinerhyundai.com,251144,Dealer Inspire',
  'https://www.missoulahyundai.com,DDC,DDC',
  'https://www.clarkhyundai.com,sincro,sincro',
  'https://www.leehyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.pecheleshyundai.com,DDC,DDC',
  'https://www.hunterhyundai.com,251144,Dealer Inspire',
  'https://www.medlinhyundai.com,DDC,DDC',
  'https://www.hyundairaleigh.com,DDC,DDC',
  'https://www.paramounthyundaivaldese.com,231,DealerOn',
  'https://www.sportdursthyundai.com,DDC,DDC',
  'https://www.bobkinghyundai.com,DDC,DDC',
  'https://www.kefferhyundai.com,DDC,DDC',
  'https://www.carolinahyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofgastonia.com,DDC,DDC',
  'https://www.lakenormanhyundai.com,231,DealerOn',
  'https://www.pinehursthyundaionline.com,251144,Dealer Inspire',
  'https://www.johnsonhyundaiofcary.com,DDC,DDC',
  'https://www.modernhyundai.com,251144,Dealer Inspire',
  'https://www.parkwayhyundai.com,DDC,DDC',
  'https://www.crenshawhyundai.com,DDC,DDC',
  'https://www.hyundaiofnewbern.com,251144,Dealer Inspire',
  'https://www.hyundaiofasheville.com,251144,Dealer Inspire',
  'https://www.hallhyundaielizabethcity.com,DDC,DDC',
  'https://www.SouthCharlotteHyundai.com,DDC,DDC',
  'https://www.bobmayberryhyundai.com,DDC,DDC',
  'https://www.capitalhyundaigreensboro.net,DDC,DDC',
  'https://www.classichyundaiwilkesboro.com,251144,Dealer Inspire',
  'https://www.capitalhyundaiofjacksonville.net,DDC,DDC',
  'https://www.deaconjoneshyundai.com,DDC,DDC',
  'https://www.flowhyundaistatesville.com,DDC,DDC',
  'https://www.johnsonhyundaiofwakeforest.com,DDC,DDC',
  'https://www.donbessettehyundai.com,DDC,DDC',
  'https://www.fargohyundai.com,DDC,DDC',
  'https://www.hyundaiofbismarck.com,251144,Dealer Inspire',
  'https://www.siddillonhyundai.com,251144,Dealer Inspire',
  'https://www.dinsdalehyundai.com,sincro,sincro',
  'https://www.woodhousehyundaiofomaha.com,251144,Dealer Inspire',
  'https://www.beardmorehyundai.com,DDC,DDC',
  'https://www.hyundaiguy.com,DDC,DDC',
  'https://www.grapponehyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofkeene.com,DDC,DDC',
  'https://www.salemhyundai.com,DDC,DDC',
  'https://www.irwinhyundai.com,231,DealerOn',
  'https://www.autofairhyundai.com,DDC,DDC',
  'https://granitehyundai.net,251144,Dealer Inspire',
  'https://www.townehyundai.com,DDC,DDC',
  'https://www.freeholdhyundai.com,DDC,DDC',
  'https://www.maxonhyundai.com,DDC,DDC',
  'https://www.circlehyundai.com,DDC,DDC',
  'https://www.paramushyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.sansoneshyundai.com,231,DealerOn',
  'https://www.burnshyundai.com,DDC,DDC',
  'https://www.hyundaiofturnersville.com,DDC,DDC',
  'https://www.libertyhyundai.com,DDC,DDC',
  'https://www.hudsonhyundai.com,DDC,DDC',
  'https://www.waynehyundai.com,251144,Dealer Inspire',
  'https://www.franklinsussexhyundai.com,DDC,DDC',
  'https://www.lynneshyundai.com,251144,Dealer Inspire',
  'https://www.causewayhyundai72.com,251144,Dealer Inspire',
  'https://www.fredbeanshyundaiflemington.com,DDC,DDC',
  'https://www.sporthyundai.net,Dealer eProcess,Dealer eProcess',
  'https://www.hyundaioftrenton.com,251144,Dealer Inspire',
  'https://www.hyundaiofburlington.com,Dealer eProcess,Dealer eProcess',
  'https://www.route1hyundai.com,DDC,DDC',
  'https://www.globalhyundainj.com,DDC,DDC',
  'https://www.vinelandhyundai.com/,Dealer eProcess,Dealer eProcess',
  'https://www.roswellhyundai.com,DDC,DDC',
  'https://www.hamiltonhyn.com,DDC,DDC',
  'https://www.fiestahyundai.com,251144,Dealer Inspire',
  'https://www.southwesthyundai.com,DDC,DDC',
  'https://www.larryhmillerhyundai.com,DDC,DDC',
  'https://www.casahyundailascruces.com/,231,DealerOn',
  'https://www.lithiahyundaireno.com,251144,Dealer Inspire',
  'https://www.carsoncityhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.centennialhyundailasvegas.com,DDC,DDC',
  'https://www.abchyundai.com,DDC,DDC',
  'https://www.hendersonhyundai.com,251144,Dealer Inspire',
  'https://www.huntingtonhyundai.com,DDC,DDC',
  'https://www.northtownhyundai.com,DDC,DDC',
  'https://www.millerhyundai.com,DDC,DDC',
  'https://www.sureskyhyundai.com,DDC,DDC',
  'https://www.prestigehyundai.net,231,DealerOn',
  'https://www.garveyhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.riverheadhyundai.com,sincro,sincro',
  'https://www.plazahyundai.com,251144,Dealer Inspire',
  'https://www.healeybrothershyundai.com,DDC,DDC',
  'https://www.fuccillohyundai.com,231,DealerOn',
  'https://www.atlantichyundai.com,DDC,DDC',
  'https://www.townehyundaibuffalo.com,251144,Dealer Inspire',
  'https://www.liahyundaiofalbany.com,231,DealerOn',
  'https://www.garveynorth.com,DDC,DDC',
  'https://www.royalhyundai.com,DDC,DDC',
  'https://www.shultshyundai.com,DDC,DDC',
  'https://www.curryhyundai.com,DDC,DDC',
  'https://www.hyundai112.com,sincro,sincro',
  'https://www.cityworldhyundai.com,DDC,DDC',
  'https://www.advantagehyundai.com,DDC,DDC',
  'https://www.starhyundai.com,251144,Dealer Inspire',
  'https://www.srhyundai.com,DDC,DDC',
  'https://www.maguirehyundai.com,DDC,DDC',
  'https://www.millenniumhyundai.com,DDC,DDC',
  'https://www.southshorehyundai.com,231,DealerOn',
  'https://www.rocklandhyundai.com,DDC,DDC',
  'https://www.myislandhyundai.com,DDC,DDC',
  'https://www.centereachhyundai.com,251144,Dealer Inspire',
  'https://www.westherrhyundai.com,231,DealerOn',
  'https://www.hyundaiof110.com,DDC,DDC',
  'https://www.matthewshyundaisyracuse.com,DDC,DDC',
  'https://www.matthewshyundaigreece.com,DDC,DDC',
  'https://www.hyundaicityny.com,dealeron,DealerOn',
  'https://www.koeppelhyundai.com,DDC,DDC',
  'https://www.MastrovitoHyundai.com,DDC,DDC',
  'https://www.shopempirehyundaiofnewrochelle.com,dealeron,DealerOn',
  'https://www.ShopEmpireHyundaiOfJamaica.com,dealeron,DealerOn',
  'https://www.matthewshyundaischenectady.com,DDC,DDC',
  'https://www.visionhyundaiwebster.com,251144,Dealer Inspire',
  'https://www.visionhyundaihenrietta.com,251144,Dealer Inspire',
  'https://www.visionhyundaicanandaigua.com,251144,Dealer Inspire',
  'https://www.maguirehyundaiofgrandisland.com,DDC,DDC',
  'https://www.hyundaicicero.com,DDC,DDC',
  'https://www.tascacentralavehyundai.com,DDC,DDC',
  'https://www.hyundaiofakron.com,DDC,DDC',
  'https://www.columbiahyundai.com,251144,Dealer Inspire',
  'https://www.tomahlhyundai.com,DDC,DDC',
  'https://www.VossHyundai.com,DDC,DDC',
  'https://www.prestonhyundai.com,251144,Dealer Inspire',
  'https://www.jeffwylerspringfieldhyundai.com,DDC,DDC',
  'https://www.mathewshyundai.com,DDC,DDC',
  'https://www.hyundaiofohio.com,DDC,DDC',
  'https://www.grahamhyundai.com,DDC,DDC',
  'https://www.crestmonthyundai.com,DDC,DDC',
  'https://www.greatlakeshyundai.com,DDC,DDC',
  'https://www.driveclassichyundai.com,251144,Dealer Inspire',
  'https://www.donwoodhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.herrnsteinhyundai.com,231,DealerOn',
  'https://www.taylorhyundaiperrysburg.com/,Dealer eProcess,Dealer eProcess',
  'https://www.coughlinhyundai.com,231,DealerOn',
  'https://www.airhyundai.com,251144,Dealer Inspire',
  'https://www.taylorhyundaifindlay.com/,Dealer eProcess,Dealer eProcess',
  'https://www.hyundaiofbedford.com,DDC,DDC',
  'https://www.elyriahyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.kenganleyhyundainorwalk.com,DDC,DDC',
  'https://www.germainhyundaiofcolumbus.com,251144,Dealer Inspire',
  'https://www.spitzerhyundaicleveland.com,251144,Dealer Inspire',
  'https://www.jeffwylerhyundaiofbeavercreek.com,DDC,DDC',
  'https://www.jeffwylerhyundaioffairfield.com,DDC,DDC',
  'https://www.jeffwylersuperiorhyundai.com,DDC,DDC',
  'https://www.victoryhyundai440.com,251144,Dealer Inspire',
  'https://www.kenganleyhyundaiparma.com,DDC,DDC',
  'https://www.kenganleyhyundainortholmsted.com,DDC,DDC',
  'https://www.diehlhyundaimassillon.com,251144,Dealer Inspire',
  'https://www.taylorhyundaitoledo.com,Dealer eProcess,Dealer eProcess',
  'https://www.glakeshyundaiofcolumbus.com,DDC,DDC',
  'https://www.glakeshyundaiofdublin.com,DDC,DDC',
  'https://www.hyundaiokc.com,sincro,sincro',
  'https://www.edmondhyundai.com,231,DealerOn',
  'https://www.billingsleyhyundai.com,DDC,DDC',
  'https://www.barrysandershyundai.com,DDC,DDC',
  'https://www.jameshodgehyundai.com/,251144,Dealer Inspire',
  'https://www.cartercountyhyundai.com,251144,Dealer Inspire',
  'https://www.regionalhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.bobhowardhyundai.com,251144,Dealer Inspire',
  'https://www.tulsahyundai.com,231,DealerOn',
  'https://www.patriothyundai.com,251144,Dealer Inspire',
  'https://www.normanhyundai.com,DDC,DDC',
  'https://www.withnellhyundai.net,DDC,DDC',
  'https://www.beavertonhyundai.com,251144,Dealer Inspire',
  'https://www.hyundaieugene.com,251144,Dealer Inspire',
  'https://www.hyundaiofportland.com,251144,Dealer Inspire',
  'https://www.dickshillsborohyundai.com/,251144,Dealer Inspire',
  'https://www.goteamhyundai.com,251144,Dealer Inspire',
  'https://www.rontonkinhyundai.com,251144,Dealer Inspire',
  'https://www.tonkingladstonehyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofalbany.com,251144,Dealer Inspire',
  'https://www.hyundaimedford.com,251144,Dealer Inspire',
  'https://www.fredbeanshyundailanghorne.com,DDC,DDC',
  'https://www.pacificohyundai.com,DDC,DDC',
  'https://www.moonhyundai.com,251144,Dealer Inspire',
  'https://www.seidelhyundai.com,DDC,DDC',
  'https://www.motorworldgrouphyundai.com,DDC,DDC',
  'https://www.davehallmanhyundai.com,DDC,DDC',
  'https://www.lehighvalleyhyundai.com,251144,Dealer Inspire',
  'https://www.freysingerHyundai1.com,251144,Dealer Inspire',
  'https://www.springfieldhyundai.com,DDC,DDC',
  'https://www.fredbeanshyundai.com,DDC,DDC',
  'https://www.cochranhyundaimonroeville.com,251144,Dealer Inspire',
  'https://www.powerofbowserhyundai.com,251144,Dealer Inspire',
  'https://www.giambalvohyundai.com,DDC,DDC',
  'https://www.laurelhyundai.net,DDC,DDC',
  'https://www.dicksoncityhyundai.com,251144,Dealer Inspire',
  'https://www.mikekellyhyundai.com,231,DealerOn',
  'https://www.autolandhyundai.com,DDC,DDC',
  'https://www.washingtonpahyundai.com,251144,Dealer Inspire',
  'https://www.cochranhyundaipittsburgh.com,251144,Dealer Inspire',
  'https://www.conicellihyundai.com,DDC,DDC',
  'https://www.delaneyhyundai.com,DDC,DDC',
  'https://www.lancasterhyundai.com,DDC,DDC',
  'https://www.cioccahyundai.com,DDC,DDC',
  'https://www.piazzahyundaipottstown.com,DDC,DDC',
  'https://www.bowserchippewa.com,251144,Dealer Inspire',
  'https://www.sunburyhyundai.com,DDC,DDC',
  'https://www.faulknerhyundaiharrisburg.com,sincro,sincro',
  'https://www.blaisealexanderhyundai.com,sincro,sincro',
  'https://www.faulknerhyundaiphilly.com,sincro,sincro',
  'https://www.piazzahyundaiwestchester.com,DDC,DDC',
  'https://www.mikecamlinhyundai.com,DDC,DDC',
  'https://www.browndaubhyundai.com,251144,Dealer Inspire',
  'https://www.cioccahyundaiofwilliamsport.com,DDC,DDC',
  'https://www.giambalvohyundaiofhanover.com,DDC,DDC',
  'https://www.kellyhyundaiofhamburg.net,231,DealerOn',
  'https://www.diehlhyundaisharon.com/,251144,Dealer Inspire',
  'https://www.bennetthyundaioflebanon.com,231,DealerOn',
  'https://www.colonialhyundai.com,DDC,DDC',
  'https://www.hyundaiofabington.com,DDC,DDC',
  'https://www.blaisehyundaialtoona.com,DDC,DDC',
  'https://www.chambersburghyundai.com,DDC,DDC',
  'https://www.delaneyhyundaidubois.com,DDC,DDC',
  'https://www.hyundaiofnewport.com,DDC,DDC',
  'https://www.griecohyundai.com,DDC,DDC',
  'https://www.nucartarboxhyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofmyrtlebeach.com,sincro,sincro',
  'https://www.dicksmithhyundai.com,DDC,DDC',
  'https://www.fortmillhyundai.com,231,DealerOn',
  'https://www.hyundaiofanderson.com,251144,Dealer Inspire',
  'https://www.bensonhyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofnorthcharleston.com,231,DealerOn',
  'https://www.almhyundai.com,DDC,DDC',
  'https://www.autonationhyundaicolumbia.com,DDC,DDC',
  'https://www.autonationhyundaihiltonhead.com,DDC,DDC',
  'https://www.terrylamberthyundai.com,231,DealerOn',
  'https://www.hyundaiofcharleston.com/,231,DealerOn',
  'https://www.hyundaiofgreer.com,DDC,DDC',
  'https://www.hyundaisiouxfalls.com,DDC,DDC',
  'https://www.libertyhyundairc.com,DDC,DDC',
  'https://www.longhyundai.net,DDC,DDC',
  'https://www.twincityhyundai.com,DDC,DDC',
  'https://www.hyundaigossett.com,DDC,DDC',
  'https://www.hyundaimountmoriah.com,DDC,DDC',
  'https://www.hyundaitn.com,Dealer eProcess,Dealer eProcess',
  'https://www.graysonhyundai.com,DDC,DDC',
  'https://www.grayeppersonhyundai.com,sincro,sincro',
  'https://www.hyundaijc.com,Dealer eProcess,Dealer eProcess',
  'https://www.wilsoncountyhyundai.com,DDC,DDC',
  'https://www.hyundaiofcoolsprings.com,DDC,DDC',
  'https://www.hyundaiofcookeville.com,231,DealerOn',
  'https://www.downtownhyundainashville.com,251144,Dealer Inspire',
  'https://www.wolfchasehyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofmurfreesboro.com,231,DealerOn',
  'https://www.hyundaiofcolumbia.com,DDC,DDC',
  'https://www.allensamuelshyundai.com,251144,Dealer Inspire',
  'https://www.tarrhyundai.com,231,DealerOn',
  'https://www.hendersonvillehyundai.com,DDC,DDC',
  'https://www.wyattjohnsonhyundai.com,231,DealerOn',
  'https://www.rustywallacehyundai.com,231,DealerOn',
  'https://www.mccombssuperiorhyundai.com,231,DealerOn',
  'https://www.huffineshyundaiplano.com,DDC,DDC',
  'https://www.freemanhyundai.com,sincro,sincro',
  'https://www.eckerthyundai.com,sincro,sincro',
  'https://www.worldcarhyundainorth.com,Dealer eProcess,Dealer eProcess',
  'https://www.autonationhyundaicorpuschristi.com,DDC,DDC',
  'https://www.wiesnerhyundai.com,DDC,DDC',
  'https://www.worldcarhyundaisouth.com,Dealer eProcess,Dealer eProcess',
  'https://www.genemesserhyundai.com,251144,Dealer Inspire',
  'https://www.roundrockhyundai.com,DDC,DDC',
  'https://www.hyundaiofabilene.com,231,DealerOn',
  'https://www.hyundaiofelpaso.com,DDC,DDC',
  'https://www.philpottmotors.net,DDC,DDC',
  'https://www.northfreewayhyundai.com,DDC,DDC',
  'https://www.perryhyundai.com,DDC,DDC',
  'https://www.humblehyundai.com,DDC,DDC',
  'https://www.dondavishyundai.com,231,DealerOn',
  'https://www.hyundaivictoria.com,231,DealerOn',
  'https://www.orrhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.hyundaiofdelrio.com,DDC,DDC',
  'https://www.hyundainorthwest.com,231,DealerOn',
  'https://www.huffineshyundaimckinney.com,DDC,DDC',
  'https://www.jerryshyundai.com,DDC,DDC',
  'https://www.sterlingmccallhyundai.com,251144,Dealer Inspire',
  'https://www.bertogdenhyundai.com,251144,Dealer Inspire',
  'https://www.demontrondhyundai.com,231,DealerOn',
  'https://www.hyundaioflongview.com,DDC,DDC',
  'https://www.amarillohyundai.com,DDC,DDC',
  'https://www.brenhamhyundai.com,DDC,DDC',
  'https://www.texanhyundai.com,DDC,DDC',
  'https://www.tiptonhyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofpharr.com,DDC,DDC',
  'https://www.baytownhyundai.com,DDC,DDC',
  'https://www.southpointhyundai.com,251144,Dealer Inspire',
  'https://www.vandergriffhyundai.com,DDC,DDC',
  'https://www.vanhyundai.com,DDC,DDC',
  'https://www.hileyhyundaiofburleson.com,Dealer eProcess,Dealer eProcess',
  'https://www.cartownsanangelo.com,DDC,DDC',
  'https://www.collegestationhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.autonationhyundainorthrichlandhills.com,DDC,DDC',
  'https://www.rockwallhyundai.net,251144,Dealer Inspire',
  'https://www.hileyhyundaioffortworth.com,251144,Dealer Inspire',
  'https://www.pattersonhyundaityler.com,DDC,DDC',
  'https://www.hyundaioflufkin.com,DDC,DDC',
  'https://www.HyundaiMesquite.com,251144,Dealer Inspire',
  'https://www.principlehyundaiboerne.com,DDC,DDC',
  'https://www.shottenkirkhyundaigranbury.com,251144,Dealer Inspire',
  'https://www.bigstarhyundai.com,251144,Dealer Inspire',
  'https://www.charlieclarkhyundailaredo.com,DDC,DDC',
  'https://www.foundationhyundaiofwichitafalls.com,DDC,DDC',
  'https://www.northwesthyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.westhoustonhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.killeenhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.Texomahyundai.com,251144,Dealer Inspire',
  'https://www.greenvillehyundai.com,251144,Dealer Inspire',
  'https://www.steelehyundaikyle.com,DDC,DDC',
  'https://www.steelehyundainewbraunfels.com,DDC,DDC',
  'https://www.mydallashyundai.com,DDC,DDC',
  'https://www.steelesouthloophyundai.com,251144,Dealer Inspire',
  'https://www.terrellhyundai.com,DDC,DDC',
  'https://www.Brookshirehyundai.com,DDC,DDC',
  'https://www.kengarffhyundaidowntown.com,251144,Dealer Inspire',
  'https://www.findlayhyundaistgeorge.com,251144,Dealer Inspire',
  'https://www.murdockhyundailindon.com,251144,Dealer Inspire',
  'https://www.murdockhyundailogan.com,251144,Dealer Inspire',
  'https://www.murdockhyundaislc.com,251144,Dealer Inspire',
  'https://www.kengarffhyundaisouthtowne.com,251144,Dealer Inspire',
  'https://www.younghyundaiutah.com,251144,Dealer Inspire',
  'https://www.pearsonhyundai.com,DDC,DDC',
  'https://www.checkeredflaghyundaiworld.com,251144,Dealer Inspire',
  'https://www.pohankahyundaiva.com,Dealer eProcess,Dealer eProcess',
  'https://WWW.HARRISONBURGHYUNDAI.COM,Dealer eProcess,Dealer eProcess',
  'https://www.westbroadhyundai.com,DDC,DDC',
  'https://www.AlexandriaHyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.duncanhyundai.com,DDC,DDC',
  'https://www.cmascolonialhyundai.com,251144,Dealer Inspire',
  'https://www.williamsburghyundai.com,DDC,DDC',
  'https://www.wrightwayhyundai.com,DDC,DDC',
  'https://www.hyundaiofchantilly.com,DDC,DDC',
  'https://www.saffordhyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofhampton.com,251144,Dealer Inspire',
  'https://www.southernteamhyundai.com,251144,Dealer Inspire',
  'https://www.cmashyundaiofwinchester.com,251144,Dealer Inspire',
  'https://www.cmashyundaioflynchburg.com,251144,Dealer Inspire',
  'https://www.saffordbrownhyundaimanassas.com,251144,Dealer Inspire',
  'https://www.saffordbrownhyundaileesburg.com,251144,Dealer Inspire',
  'https://www.saffordbrownhyundaifairfax.com,251144,Dealer Inspire',
  'https://www.priorityhyundai.com,231,DealerOn',
  'https://SouthernHyundaiNewportNews.com,251144,Dealer Inspire',
  'https://SouthernHyundaiChesapeake.com,251144,Dealer Inspire',
  'https://www.flowhyundaicharlottesville.com,DDC,DDC',
  'https://www.Koonswoodbridgehyundai.com,231,DealerOn',
  'https://www.hyundaivt.com,DDC,DDC',
  'https://www.McGeeHyundai.com,DDC,DDC',
  'https://www.vancouverhyundai.com,sincro,sincro',
  'https://www.larsonhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.dougshyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.korumhyundai.com,DDC,DDC',
  'https://www.tituswillhyundai.com,DDC,DDC',
  'https://www.speckhyundai.com,251144,Dealer Inspire',
  'https://www.hyundaiofbellingham.com,251144,Dealer Inspire',
  'https://www.skagithyundai.com,DDC,DDC',
  'https://www.carproshyundai.com,DDC,DDC',
  'https://www.budclaryauburnhyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.haselwoodhyundai.com,DDC,DDC',
  'https://www.seattlehyundai.com,Dealer eProcess,Dealer eProcess',
  'https://www.hyundaiofeverett.com,DDC,DDC',
  'https://www.spokanehyundai.net,251144,Dealer Inspire',
  'https://www.hyundaiofkirkland.com,DDC,DDC',
  'https://www.budclaryhyundai.com,DDC,DDC',
  'https://www.hyundaiofyakima.com,251144,Dealer Inspire',
  'https://www.kenvancehyundai.com,251144,Dealer Inspire',
  'https://www.boucherhyundai.com,251144,Dealer Inspire',
  'https://www.zimbrickhyundaiwest.com,231,DealerOn',
  'https://www.vhhyundaisheboygan.com,DDC,DDC',
  'https://www.johnamatohyundai.com,251144,Dealer Inspire',
  'https://www.vhhyundaifonddulac.com,DDC,DDC',
  'https://www.dahlhyundai.com,251144,Dealer Inspire',
  'https://www.zimbrickhyundaieastside.com,DDC,DDC',
  'https://www.hyundaiwausau.com,DDC,DDC',
  'https://www.bergstromhyundaiappleton.com,sincro,sincro',
  'https://www.boucherhyundaijanesville.com,251144,Dealer Inspire',
  'https://www.hyundaiwestallis.com,DDC,DDC',
  'https://www.rosenhyundaikenosha.com,DDC,DDC',
  'https://www.rosenhyundaigreenfield.com,251144,Dealer Inspire',
  'https://www.stevenspointhyundai.com,251144,Dealer Inspire',
  'https://www.northshorehyundai.com,251144,Dealer Inspire',
  'https://www.zeiglerhyundairacine.com,251144,Dealer Inspire',
  'https://www.hyundaigreenbay.com,sincro,sincro',
  'https://www.straubhyundai.com,251144,Dealer Inspire',
  'https://www.dutchmillerhyundai.com,231,DealerOn',
  'https://www.joehollandhyundai.com,251144,Dealer Inspire',
  'https://www.superiorhyundaiwv.com,231,DealerOn',
  'https://www.jenkinshyundaiwv.com,DDC,DDC',
  'https://www.weimerhyundai.com,DDC,DDC',
  'https://www.hyundaiwv.com,231,DealerOn',
  'https://www.hyundaiofbeckley.com,231,DealerOn',
  'https://www.kengarffhyundaicheyenne.com,251144,Dealer Inspire',
]

for (const site of sites)
  test(site, async ({ page, context, collects_ga4 }) => {
    await context.route(/facebook|google.*collect|bing|liveshopping/, async (route, request) => await route.abort())
    await enableGADebug(context) // para não realizar batch de eventos e terminar o teste mais rápido

    const [url, meta_pid, ga4_pid] = site.split(',')

    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 20000 })

    // 1- Valida que tem acesso à página daqui do Brasil
    const pageTitle = await page.title()
    expect(pageTitle, 'ERRO: Acesso bloqueado em BR').not.toBe('Access denied')

    // 2- Valida que a meta tag existe no DOM
    let meta = await page.evaluate(() => document.querySelector('meta[name="providerID"]'))
    if (!meta) {
      await page.waitForLoadState('networkidle')
      meta = await page.evaluate(() => document.querySelector('meta[name="providerID"]'))
      if (meta)
        expect
          .soft(
            false,
            'ERRO: a meta tag foi definida, porém de forma lazy - pode causar intermitência no envio de ep.provider_id'
          )
          .toBeTruthy()
      else expect.soft(false, 'ERRO: a meta tag não foi definida no DOM').toBeTruthy()
    }

    // 3- Valida que a meta tag possui o valor esperado
    await expect
      .soft(
        page.evaluate(() => document.querySelector('meta[name="providerID"]')?.content),
        'ERRO: a meta tag está com valor diferente do esperado.'
      )
      .resolves.toBe(meta_pid)

    // 4- Valida que o valor da meta tag pode ser capturado via variável global, que é como está configurado no GTM
    await expect
      .soft(
        page.evaluate(() => document.head.children?.providerID?.content),
        'ERRO: a meta tag não está disponível como variável global, e portanto não pode ser capturada pelo GTM em sua configuração atual'
      )
      .resolves.toBeTruthy()

    // 5- Valida que teve disparo de page_view de GA4 em até 30s
    try {
      await collects_ga4.waitForMessage({
        timeout: 30000,
        regex: /en=page_view/,
        timeoutMessage: 'Timeout aguardando o page_view de GA4',
      })
    } catch (error) {}

    // 6- Valida que o page_view veio antes de 30s
    expect.soft(collects_ga4.messages.length, 'ERRO: o page_view de GA4 não disparou em 30s').toBeGreaterThanOrEqual(1)

    // Se não teve nenhum page_view, não faz sentido realizar os testes abaixo
    if (collects_ga4.messages.length === 0) return

    // Aguarda mais alguns segundos para pegar possíveis duplicações de page_view
    await page.waitForTimeout(4000)

    // 7- Valida que teve exatamente 1 page_view
    expect.soft(collects_ga4.messages.length, 'ERRO: deveria ter só 1 page_view de GA4').not.toBeGreaterThan(1)

    // 8- Valida que ep.provider_id foi passado na tag de page_view
    expect(collects_ga4.messages[0], 'ERRO: o ep.provider_id de GA4 não foi enviado').toMatch('&ep.provider_id=')
    expect
      .soft(collects_ga4.messages[0], 'ERRO: o ep.provider_id de GA4 foi enviado, porém não possui o valor esperado')
      .toMatch(`ep.provider_id=${encodeURIComponent(ga4_pid)}`)
  })

test.afterEach(async ({ page, context }) => {
  await page.close()
  await context.close()
})
